apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-secrets
  namespace: open-webui
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: openwebui-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        TOOL_SERVER_CONNECTIONS: '{{ list (dict "url" "http://higress-internal.higress-system.svc.cluster.local/mcp/servers/memory-service" "path" "" "type" "mcp" "auth_type" "bearer" "key" .OPENAI_API_KEY "config" (dict "enable" true) "info" (dict "id" "memory-service" "name" "memory-service" "description" "h8s MCP memory service (shared memory store)")) | toJson }}'
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: higress/api-keys/open-webui
        property: api-key
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: authelia/openwebui-oidc
        property: client-secret-plaintext
    - secretKey: WEBUI_SECRET_KEY
      remoteRef:
        key: openwebui/secret-key
        property: secret-key
