apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-secrets
  namespace: open-webui
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: openwebui-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: higress/api-keys/open-webui
        property: api-key
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: authelia/openwebui-oidc
        property: client-secret-plaintext
    - secretKey: WEBUI_SECRET_KEY
      remoteRef:
        key: openwebui/secret-key
        property: secret-key
