apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-mlflow-creds
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: garage-mlflow-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: access-key-id
      remoteRef:
        key: garage/mlflow-garage-credentials
        property: access-key-id
    - secretKey: secret-access-key
      remoteRef:
        key: garage/mlflow-garage-credentials
        property: secret-access-key
