# https://artifacthub.io/packages/helm/cilium/cilium/1.20.0-pre.3?modal=values
operator:
  enabled: true
  replicas: 1

l2announcements:
  enabled: true

gatewayAPI:
  enabled: true
  enableAlpn: true
  enableAppProtocol: true

kubeProxyReplacement: true

hubble:
  relay:
    enabled: true
  ui:
    enabled: true
