apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: harbor-external-auth-authelia
  namespace: authelia
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: harbor
  to:
    - group: ""
      kind: Service
      name: authelia
