apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: GF_SECURITY_ADMIN_PASSWORD
type: Opaque
data:
  GF_SECURITY_ADMIN_USER: YWRtaW4=
