apiVersion: v1
kind: Secret
metadata:
  name: grafana-oidc-client-secret
  namespace: monitoring
  annotations:
    secret-generator.v1.mittwald.de/copy-from-secret-name: authelia-oidc-client-secrets
    secret-generator.v1.mittwald.de/copy-from-secret-namespace: authelia
type: Opaque
