apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-github-token
  namespace: renovate-operator
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: renovate-secret
    creationPolicy: Orphan
    deletionPolicy: Retain
    template:
      data:
        RENOVATE_TOKEN: "{{ .token }}"
        GITHUB_COM_TOKEN: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: renovate/github
        property: token
