apiVersion: v1
kind: Secret
metadata:
  name: cnpg-harbor-user-credentials
  namespace: harbor
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/type: string
type: Opaque
stringData:
  username: harbor
