apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-default-cluster
  namespace: cloudnative-pg
spec:
  description: Default postgres cluster
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  instances: 3
  postgresql:
    parameters:
      max_connections: "100"
  storage:
    size: 32Gi
  resources:
    requests:
      memory: 256Mi
  managed:
    roles:
      - name: admin
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: pg-default-credentials
          key: password
