apiVersion: v1
kind: Secret
metadata:
  name: cnpg-authentik-user-credentials
  namespace: authentik
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/type: string
type: Opaque
stringData:
  username: authentik
