apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bytestash-jwt
  namespace: bytestash
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: bytestash-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: bytestash/jwt
        property: secret
    - secretKey: token-expiry
      remoteRef:
        key: bytestash/jwt
        property: token-expiry
