apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bytestash-oidc
  namespace: bytestash
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: bytestash-oidc
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client-secret
      remoteRef:
        key: bytestash/oidc
        property: client-secret-plaintext
