apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-garage-creds
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: mlflow-garage-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: accessKeyId
      remoteRef:
        key: garage/mlflow-garage-credentials
        property: access-key-id
    - secretKey: secretAccessKey
      remoteRef:
        key: garage/mlflow-garage-credentials
        property: secret-access-key
