apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-oidc
  namespace: mlflow
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: mlflow-oidc-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: authelia/mlflow-oidc
        property: client-secret-plaintext
    - secretKey: SECRET_KEY
      remoteRef:
        key: mlflow/oidc
        property: secret-key
