apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-admin-password
  namespace: authelia
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: authelia-admin-password
    creationPolicy: Orphan
    deletionPolicy: Retain
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: authelia-admin-password-generator
