apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-bytestash-client-secret
  namespace: authelia
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: authelia-bytestash-client-secret
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: client-secret-hash
      remoteRef:
        key: authelia/bytestash-oidc
        property: client-secret-hash
