apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-authelia-user-credentials
  namespace: authelia
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: cnpg-authelia-user-credentials
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: cnpg/authelia-user-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: cnpg/authelia-user-credentials
        property: password
