apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: authelia-grafana-client-secret-push
  namespace: authelia
spec:
  refreshInterval: 5m
  secretStoreRefs:
    - name: vault-cluster-secretstore
      kind: ClusterSecretStore
  selector:
    secret:
      name: authelia-grafana-client-secret
  data:
    - match:
        secretKey: client-secret
        remoteRef:
          remoteKey: authelia/grafana-oidc
          property: client-secret
  deletionPolicy: None
