apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: authelia-grafana-client-secret-generator
  namespace: authelia
spec:
  length: 64
  allowRepeat: true
  noUpper: false
