apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-session-secret
  namespace: authelia
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: authelia-session-secret
    creationPolicy: Orphan
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        value: '{{ .password }}'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: authelia-session-secret-generator
