# https://raw.githubusercontent.com/goauthentik/helm/refs/tags/authentik-2026.5.2/charts/authentik/values.yaml

authentik:
  disable_startup_analytics: true
  secret_key: ""
  log_level: info
  error_reporting:
    enabled: false
  postgresql:
    host: cnpg-authentik-rw.authentik.svc.cluster.local
    name: authentik
    user: authentik
    password: ""
    port: 5432
    use_pgpool: false
  redis:
    host: redis.authentik.svc.cluster.local
    port: 6379
    db: 0

postgresql:
  enabled: false

blueprints:
  configMaps:
    - authentik-google-blueprint

server:
  replicas: 1
  service:
    type: ClusterIP
  ingress:
    enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secret-key
          key: secret_key
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: cnpg-authentik-user-credentials
          key: password

worker:
  replicas: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secret-key
          key: secret_key
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: cnpg-authentik-user-credentials
          key: password
