apiVersion: v1
kind: Secret
metadata:
  name: cnpg-openwebui-user-credentials
  namespace: open-webui
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/type: string
type: Opaque
stringData:
  username: openwebui
