apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-token
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: cloudflared-token
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        key: kubernetes-homelab/data/cloudflare/tunnel
        property: private-key
