apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: excalidraw-homelab-local
  namespace: excalidraw
spec:
  secretName: excalidraw-homelab-local-tls
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  commonName: excalidraw.drmarchent.com
  dnsNames:
    - excalidraw.drmarchent.com
