apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-homelab-local
  namespace: longhorn-system
spec:
  secretName: longhorn-homelab-local-tls
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  commonName: longhorn.drmarchent.com
  dnsNames:
    - longhorn.drmarchent.com
