apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mlflow-homelab-local
  namespace: mlflow
spec:
  secretName: mlflow-homelab-local-tls
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  commonName: mlflow.drmarchent.com
  dnsNames:
    - mlflow.drmarchent.com
