apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-mlflow
  namespace: mlflow
spec:
  description: Postgres cluster for MLflow
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  instances: 1
  storage:
    size: 1Gi
  managed:
    roles:
      - name: mlflow
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: cnpg-mlflow-user-credentials
          key: password
  enableSuperuserAccess: false
