apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-dex-authelia-client-secret
  namespace: argocd
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
    deletionPolicy: Retain
  data:
    - secretKey: dex.authelia.clientSecret
      remoteRef:
        key: authelia/argocd-oidc
        property: client-secret-plaintext
