apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: endurain-admin-credentials
  namespace: endurain
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: endurain-admin-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: endurain/admin-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: endurain/admin-credentials
        property: password
