apiVersion: apps/v1
kind: Deployment
metadata:
  name: endurain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: endurain
  template:
    metadata:
      labels:
        app: endurain
    spec:
      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: endurain
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          image: codeberg.org/endurain-project/endurain:v0.19
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: TZ
              value: Europe/London
            - name: ENDURAIN_HOST
              value: https://endurain.drmarchent.com
            - name: BEHIND_PROXY
              value: "true"
            - name: ENVIRONMENT
              value: production
            - name: DB_TYPE
              value: postgres
            - name: DB_HOST
              value: cnpg-endurain-rw.endurain.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: endurain
            - name: DB_DATABASE
              value: endurain
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cnpg-endurain-user-credentials
                  key: password
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: endurain-secret-key
                  key: secret_key
            - name: FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: endurain-fernet-key
                  key: fernet_key
            - name: RATE_LIMIT_STORAGE_URI
              value: memory://
            - name: AUTH_SECURITY_STORAGE_URI
              value: memory://
          volumeMounts:
            - name: endurain-data
              mountPath: /app/backend/data
              subPath: data
            - name: endurain-data
              mountPath: /app/backend/logs
              subPath: logs
      volumes:
        - name: endurain-data
          persistentVolumeClaim:
            claimName: endurain-data
