apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: endurain-fernet-key
  namespace: endurain
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: endurain-fernet-key
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: fernet_key
      remoteRef:
        key: endurain/fernet-key
        property: fernet_key
