apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: endurain
resources:
  - ./pvc.yaml
  - ./secret-key-externalsecret.yaml
  - ./fernet-key-externalsecret.yaml
  - ./deployment.yaml
  - ./service.yaml
