apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: endurain-secret-key
  namespace: endurain
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: endurain-secret-key
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: secret_key
      remoteRef:
        key: endurain/secret-key
        property: secret_key
