# Terminate SSL at ingress
configs:
  cm:
    resource.compareoptions: |
      ignoreResourceStatusField: all
    admin.enabled: true
    url: https://argocd.drmarchent.com
    dex.config: |
      connectors:
        - type: oidc
          id: authelia
          name: Authelia
          config:
            issuer: https://auth.drmarchent.com
            clientID: argocd
            clientSecret: $dex.authelia.clientSecret
            insecureEnableGroups: true
            scopes:
              - openid
              - profile
              - email
              - groups
  params:
    server.insecure: true
  rbac:
    create: true
    scopes: "[groups]"
    policy.default: ""
    policy.csv: |
      g, admins, role:admin

controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

server:
  extraArgs:
    - --insecure
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

redis:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

dex:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

notifications:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true