apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: default-key
spec:
  clusterRef:
    name: garage-default-cluster
  bucketPermissions:
    - bucketRef:
        name: default
      read: true
      write: true
