apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageKey
metadata:
  name: default-key
spec:
  clusterRef:
    name: garage-default-cluster
  bucketPermissions:
    - bucketRef: default
      read: true
      write: true
