apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: grafana-httpproxy
  namespace: grafana
spec:
  routes:
    - conditions:
      - prefix: /
      services:
        - name: grafana-service 
          port: 3000
  virtualhost:
    fqdn: grafana.homelab.local
