apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: grafana-httpproxy
  namespace: grafana
spec:
  routes:
    - conditions:
      - prefix: /
      services:
        - name: nginx-hello-world
          port: 80
  virtualhost:
    fqdn: helloworld.homelab.local
