apiVersion: v1
kind: ConfigMap
metadata:
  name: corefile-coredns-lan
  namespace: coredns-lan
data:
  Corefile: |-
    homelab.local:53 {
        forward . 192.168.172.12
        log
        errors
        cache 30
        ready
    }
