apiVersion: v1
kind: Service
metadata:
  name: coredns-lan
  namespace: coredns-lan
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9153"
  labels:
    k8s-app: coredns-lan
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.178.11
  selector:
    k8s-app: coredns-lan
  ipFamilyPolicy: SingleStack
  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
    - name: metrics
      port: 9153
      protocol: TCP
