apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-internal-secrets
  namespace: harbor
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: harbor-internal-secrets
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: secret
      remoteRef:
        key: harbor/internal-secrets
        property: secret
    - secretKey: CSRF_KEY
      remoteRef:
        key: harbor/internal-secrets
        property: CSRF_KEY
    - secretKey: secretKey
      remoteRef:
        key: harbor/internal-secrets
        property: secretKey
    - secretKey: tls.key
      remoteRef:
        key: harbor/internal-secrets
        property: tls.key
    - secretKey: tls.crt
      remoteRef:
        key: harbor/internal-secrets
        property: tls.crt
    - secretKey: JOBSERVICE_SECRET
      remoteRef:
        key: harbor/internal-secrets
        property: JOBSERVICE_SECRET
    - secretKey: REGISTRY_HTTP_SECRET
      remoteRef:
        key: harbor/internal-secrets
        property: REGISTRY_HTTP_SECRET
    - secretKey: REGISTRY_PASSWD
      remoteRef:
        key: harbor/internal-secrets
        property: REGISTRY_PASSWD
    - secretKey: REGISTRY_HTPASSWD
      remoteRef:
        key: harbor/internal-secrets
        property: REGISTRY_HTPASSWD
