
externalURL: https://harbor.drmarchent.com
expose:
  type: clusterIP
  tls:
    enabled: false
existingSecretAdminPassword: harbor-admin-credentials
existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
database:
  type: external
  external:
    host: cnpg-harbor-rw.harbor.svc.cluster.local
    port: 5432
    username: harbor
    coreDatabase: harbor_core
    existingSecret: cnpg-harbor-user-credentials
metrics:
  enabled: true
  serviceMonitor:
    enabled: true

persistence:
  enabled: true

updateStrategy:
  type: Recreate

existingSecretSecretKey: harbor-internal-secrets

core:
  existingSecret: harbor-internal-secrets
  secretName: harbor-internal-secrets
  existingXsrfSecret: harbor-internal-secrets
  existingXsrfSecretKey: CSRF_KEY

jobservice:
  existingSecret: harbor-internal-secrets
  existingSecretKey: JOBSERVICE_SECRET

registry:
  existingSecret: harbor-internal-secrets
  existingSecretKey: REGISTRY_HTTP_SECRET
  credentials:
    existingSecret: harbor-internal-secrets
