apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: coredns-lan-pool
spec:
  blocks:
    - cidr: 192.168.178.11/32
  serviceSelector:
    matchLabels:
      k8s-app: coredns-lan
