apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-secret
  namespace: searxng
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: searxng-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: SECRET
      remoteRef:
        key: searxng/searxng-secret
        property: SECRET
    - secretKey: METRICS_PASSWORD
      remoteRef:
        key: searxng/searxng-secret
        property: METRICS_PASSWORD
    - secretKey: METRICS_USERNAME
      remoteRef:
        key: searxng/searxng-secret
        property: METRICS_USERNAME
