apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  name: mcp-router
  namespace: higress-system
spec:
  url: oci://higress-registry.us-west-1.cr.aliyuncs.com/plugins/mcp-router:2.0.2
  imagePullPolicy: IfNotPresent
  failStrategy: FAIL_CLOSE
  priority: 940
  defaultConfig:
    servers:
      - name: searxng
        path: /mcp/servers/searxng
  matchRules:
    - ingress:
        - mcp-unified
      configDisable: false
      config:
        enable: true
