apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-google-oauth
  namespace: authentik
spec:
  refreshInterval: 87600h
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: authentik-google-oauth-credentials
  data:
    - secretKey: client_id
      remoteRef:
        key: kubernetes-homelab/authentik/google-oauth
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: kubernetes-homelab/authentik/google-oauth
        property: client_secret
