apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./opencode-go-externalsecret.yaml
  - ./mcpbridge.yaml
  - ./ingresses
  - ./wasmplugins/model-router.yaml
  - ./wasmplugins/ai-proxy-opencode-go.yaml
  - ./wasmplugins/ai-proxy-opencode-zen.yaml
  - ./wasmplugins/model-aggregator.yaml
