apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./opencode-go-externalsecret.yaml
  - ./mcpbridge.yaml
  - ./ingress.yaml
  - ./wasmplugins/opencode-go.yaml
  - ./wasmplugins/model-aggregator.yaml
