apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./opencode-go-externalsecret.yaml
  - ./openrouter-externalsecret.yaml
  - ./api-key-externalsecret.yaml
  - ./mcpbridge.yaml
  - ./higress-internal-service.yaml
  - ./ingresses
  - ./wasmplugins/key-auth.yaml
  - ./wasmplugins/model-router.yaml
  - ./wasmplugins/ai-proxy-opencode-go.yaml
  - ./wasmplugins/ai-proxy-opencode-zen.yaml
  - ./wasmplugins/ai-proxy-openrouter.yaml
  - ./wasmplugins/model-aggregator.yaml
  - ./wasmplugins/ai-statistics.yaml
