apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: higress-opencode-go
  namespace: higress-system
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: higress-opencode-go
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: api-token-1
      remoteRef:
        key: higress/opencode-go
        property: api-token-1
    - secretKey: api-token-2
      remoteRef:
        key: higress/opencode-go
        property: api-token-2
