apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./gateways/cloudflared-tunnel.yaml
  - ./gateways/lan.yaml
  - ./http-routes/argocd.yaml
  - ./http-routes/garage.yaml
  - ./http-routes/grafana.yaml
  - ./http-routes/harbor.yaml
  - ./http-routes/authentik.yaml
  - ./http-routes/endurain.yaml
  - ./http-routes/hello-world.yaml
  - ./http-routes/hubble.yaml
  - ./http-routes/renovate.yaml
  - ./http-routes/http-to-https-redirect.yaml
  - ./reference-grants/lan-gateway-argocd-tls.yaml
  - ./reference-grants/lan-gateway-authentik-tls.yaml
  - ./reference-grants/lan-gateway-endurain-tls.yaml
  - ./reference-grants/lan-gateway-garage-tls.yaml
  - ./reference-grants/lan-gateway-grafana-tls.yaml
  - ./reference-grants/lan-gateway-harbor-tls.yaml
  - ./reference-grants/harbor-external-auth-authentik.yaml
  - ./reference-grants/lan-gateway-hello-world-tls.yaml
  - ./reference-grants/lan-gateway-renovate-tls.yaml
  - ./reference-grants/lan-gateway-hubble-tls.yaml
patches:
  - target:
      kind: ReferenceGrant
    patch: |
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "1"
  - target:
      kind: Gateway
    patch: |
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "2"
  - target:
      kind: HTTPRoute
    patch: |
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "3"
